import gnupg
# gnupg.__version__
gpg = gnupg.GPG(gnupghome='/etc/salt/gpgkeys')

create_params = {
    'key_type': 'RSA',
    'key_length': 2048,
    'name_real': 'Foobian',
    'name_comment': 'Generated by PyREPL',
    'name_email': 'foobian@example.com'
}

input_data = gpg.gen_key_input(**create_params)
key = gpg.gen_key(input_data)

print(key.fingerprint)
