gpg.create_key:
  module.run:
    - key_type: RSA
    - key_length: 2048
    - name_real: Salt Master
    - name_comment: Generated by Salt
    - name_email: {{ salt['pillar.get']('gpg:email') }}
    - user: {{ salt['pillar.get']('gpg:user') }}
